### ISSUE TITLE
Sample coding

### ISSUE THREAD

**Issue by rakeshkeerthi** [KayLerch/alexa-skills-kit-tellask-java#2]
Hi Kay,

 Sorry to post this here though this is not an issue.

I' am an Alexa developer(Java) and I code the way that is given in the amazon sample code library.

I've seen your code, but sorry to say that I didn't understand this quite well.(Problem from my end, not your end). As this is divided into multiple files and you are using an YAML instead of the regular utterances and intents in the UI, also the divided files are confusing me a lot on terms like where does the flow start from and on how it goes on.

Can you please make one of the sample codes in the way that you created this, so that I can match the sample code(the default provided by alexa) to this and understand on how to be a better coder in terms of following the semantics and make it more readable and user friendly.

I request you to do it using the sessions example(the colors)

Thanks & Regards,
Rakesh

**Comment by KayLerch** [comment]
Hi Rakesh,

thanks for your feedback. I was spending some time documenting this SDK in order to have a good start - but maybe it is still not self-explaining. Did you have a look at the calculator-sample in the samples-folder? 

The goal of this SDK is to simplify and sometimes this also leads to more intransparency of what is actually happening behind the scenes. The minimal set-up for a Tellask-skill is:
- one utterances.yml
- one AlexaRequestStreamHandler to reference an applicationId (skillId) and the utterances.yml. This class is the actual entrance to your skill
- one LaunchIntentHandler that handles the initial request ("Alexa, start my skill")
All the rest is optional.

You create as much IntentHandlers as you have intents defined in your Alexa skill. Just by tagging the classes with an @AlexaIntentListener subscribes them to all corresponding intents coming in to your skill.  Dispatching the skill requests to those intent handlers is nothing you have to deal with in Tellask SDK. 

In one line: with Tellask SDK you focus on the actual implementation of Alexa skill logic in so-called IntentHandlers without needing to parse JSON input and generate JSON output.
